server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: ordo-application
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ordo}
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      path-mapping:
        prometheus: metrics
      base-path: /
