package com.github.gustavoflor.ordo.core.entity;

public enum Origin {
    ACADEMIC_RESEARCHER,
    HEALTH_AGENT,
    AMNESIC,
    ARTIST,
    ATHLETE,
    CHIEF,
    CRIMINAL,
    REPENTANT_CULTIST,
    ENGINEER,
    EXECUTIVE,
    INVESTIGATOR,
    FIGHTER,
    TYCOON,
    MERCENARY,
    MILITARY,
    OPERATOR,
    POLICE,
    RELIGIOUS,
    FEDERAL_WORKER,
    CONSPIRACY_THEORIST,
    INFORMATION_TECHNICIAN,
    RURAL_WORKER,
    UNIVERSITY_STUDENT,
    VICTIM
}
